### PR TITLE
Bump openshift/prometheus to v2.35.0

### PR DESCRIPTION
**Pull request by arajkumar**
Bumping the version manually due to the failure of https://github.com/rhobs/syncbot/runs/6122107778?check_suite_focus=true which can't be automatically fixed by the bot.

### CODE REVIEW

**Comment by simonpasquier** [comment]
My suspicion is that we need to remove `web/ui/assets_vfsdata.go` because of #10220 (ping @jan--f).

**Comment by jan--f** [comment]
> My suspicion is that we need to remove `web/ui/assets_vfsdata.go` because of [prometheus#10220](https://github.com/prometheus/prometheus/pull/10220) (ping @jan--f).

Yes, thats correct. We can drop [the asset generation](https://github.com/rhobs/syncbot/blob/main/.github/workflows/merge-prometheus.yaml#L21-L24), this should work automatically now.

**Comment by arajkumar** [comment]
common-tests seem to be using go1.16 image which is not desired.

Screenshot 2022-05-03 at 7 33 35 AM

Hopefully https://github.com/openshift/release/pull/28275 should fix the problem.

**Pull request merged**
