### PR TITLE
Bump to v2.10.0

### PR DESCRIPTION
**Pull request by simonpasquier**
cc @brancz 
Not be merged immediately as 2.10.0 is the brand new version and I need to test that https://github.com/prometheus/prometheus/pull/5582 didn't break the alerting console. Other than that, there should some nice performance improvements compared to v2.7.2 that is the previously shipped version.

### CODE REVIEW

**Comment by simonpasquier** [comment]
Alert console seems to be ok:

image

**Comment by brancz** [comment]
Nice!

**Pull request merged**
