### PR TITLE
Bug 1925061: disable using MADV_FREE to release unused memory

### PR DESCRIPTION
**Pull request by paulfantom**
As in title. This is for testing a possible solution to OOMKilling prometheus during upgrades.

/cc @s-urbaniak @sdodson @bparees

### CODE REVIEW

**Comment by bparees** [comment]
pre-emptively group-lead-approving so you can merge it if it helps.

**Comment by smarterclayton** [comment]
I don't see how MADV_FREE fixes the issue.  This is real memory that prometheus has to track.  I still see a doubling of prometheus memory use over the entire run

**Comment by rphillips** [comment]
MADV_FREE may decrease the memory usage on compaction... it is worth the test to see if it helps.

**Comment by smarterclayton** [comment]
image

Upgrade is in the middle, I still see 2x growth in upgrade.

**Comment by simonpasquier** [comment]
IIUC `MADV_FREE` should already be set by the base image in 4.7 thanks to https://github.com/openshift/images/pull/61?

**Comment by rphillips** [comment]
@simonpasquier I just checked my 4.7 cluster and the madvdontneed option is not enabled.

It looks like enabling the option might be recommended from upstream now: https://github.com/prometheus/prometheus/issues/8357#issuecomment-766346002

**Comment by rphillips** [comment]
I tweaked the registry.ci.openshift.org/ocp/4.7:base image which is not being used here.

**Comment by simonpasquier** [comment]
> I tweaked the registry.ci.openshift.org/ocp/4.7:base image which is not being used here.

Right i was confused about which base image is used for Prometheus. It shouldn't hurt to use `MADV_DONTNEED` but I'm afraid it won't help much for bug 1925061 since we're not seeing memory increase due to compaction (or any other transient task which should release memory as fast as possible once it's completed).

**Pull request closed without merging**
