### PR TITLE
MON-1175: Revert "web/ui: disable React-based UI"

### PR DESCRIPTION
**Pull request by dgrisonnet**
This PR bumps Prometheus to v2.23.0 and re-enable the React-base UI.
Note that this UI is now the default one in Prometheus and there is a link to get back to the old UI if needed.

### CODE REVIEW

**Comment by simonpasquier** [comment]
Can you include the bump to v2.23.0 in this PR too? You'd have to run `make build` and commit the Javascript deps in addition.

**Comment by dgrisonnet** [comment]
@simonpasquier I bumped Prometheus to v2.23.0

**Comment by lilic** [comment]
Side note: This needs a bump of Prometheus version afterward as well, in CMO and ideally upstream as well, so we have it tested against this version https://github.com/prometheus-operator/prometheus-operator/blob/cf03980714e6148870040ad0f744a17087e88f00/pkg/operator/defaults.go#L78 Thanks!

**Comment by simonpasquier** [comment]
/lgtm

Tested locally and works great for me.

**Pull request merged**
