### PR TITLE
OCPBUGS-2873: fix certificate reloads after rotation

### PR DESCRIPTION
**Pull request by simonpasquier**
When the TLS certificate (used by Prometheus to authenticate to the
scraped targets) gets rotated, Prometheus doesn't pick up the new
certificate until the connection to the target is re-established.
Because Prometheus uses keep-alive HTTP connections, the consequence is
that the scrapes start failing after about 1 day and the TargetDown
alert fires.

There's an upstream pull request [1] to address the issue but it isn't
merged yet. This commit pulls the changes from [1] into our downstream
fork by adding a replace directive to go.mod for the
github.com/prometheus/common. The replacement code is under
patches/github.com/prometheus/common which is the same version as
upstream (v0.37.0) + the upstream PR applied on top of it.

As soon as upstream Prometheus depends on a version of
github.com/prometheus/common that fixes the issue, the replace directive
in go.mod and the code under the patches/ directory can be removed.

[1] https://github.com/prometheus/common/pull/345

### CODE REVIEW

**Comment by raptorsun** [comment]
Is the fix to reloading certificates lying in the file `vendor/github.com/prometheus/common/config/http_config.go`, adding keyfile and cert file into `tlsRoundTripper`?

**Comment by simonpasquier** [comment]
> Is the fix to reloading certificates lying in the file `vendor/github.com/prometheus/common/config/http_config.go`, adding keyfile and cert file into `tlsRoundTripper`?

yes, this is a copy/paste from https://github.com/prometheus/common/pull/345

**Comment by simonpasquier** [comment]
> > > Is the fix to reloading certificates lying in the file `vendor/github.com/prometheus/common/config/http_config.go`, adding keyfile and cert file into `tlsRoundTripper`?
> > 
> > 
> > yes, this is a copy/paste from [prometheus/common#345](https://github.com/prometheus/common/pull/345)
> 
> Can't we force a certificate rotation ahead of schedule?

Unfortunately I haven't a way to decrease the validity period of the generated certificates.

**Comment by raptorsun** [comment]
It is strange the metric `prometheus_remote_storage_samples_pending` that the test code is looking for does not exist in Prometheus.

image

**Comment by simonpasquier** [comment]
https://github.com/prometheus/common/pull/345 has been merged.

**Comment by juzhao** [comment]
since we can not verify the bug with cluster-bot cluster(the cluster would be automatically destroyed within ~3 hours ), will verify the bug after the code merged to payload and will let the cluster run for more than 1 day then monitor if the targets are down
/label qe-approved

**Comment by simonpasquier** [comment]
thanks @juzhao for what is worth, there's a unit test for the change so I'm reasonably optimistic that it will fix the issue.

**Pull request merged**
