### PR TITLE
[MON-1969] Update scripts/rh-manifest.sh replacing yarn by npm

### PR DESCRIPTION
**Pull request by raptorsun**
This PR updates `scripts/rh-manifest.sh`, replacing yarn by npm, [following the switch from yarn to npm by upstream](https://github.com/prometheus/prometheus/commit/7291563d4d0bdb850a602d682838ae2896f2c3d2).

The new script gathers only production dependencies together and setup a fake project to resolve all derivative dependencies. Then we update `rh-manifest.txt` with the dependency list of this fake project.

[JIRA ticket here](https://issues.redhat.com/browse/MON-1969)

### CODE REVIEW

**Comment by bison** [comment]
This looks good to me, but I still have the feeling we could simplify it. I'm pretty sure we can just replace the `find` command in the script with:

```
find . -name package.json -execdir npm list --prod --json --all --package-lock-only \; | \
  jq -r '..|objects|to_entries|.[]|select(.value.version?) | "\(.key) \(.value.version)"' \
    >>"${WORKING_FILE}"
```

That produces the same output that's here, minus 3 optional dependencies, which I think is fine.

**Review by bison — APPROVED** [review]
/lgtm

**Comment by arajkumar** [comment]
@raptorsun Looks like this is broken in prometheus as most of the components are using `yarn` not `npm`.

**Comment by raptorsun** [comment]
> @raptorsun Looks like this is broken in prometheus as most of the components are using `yarn` not `npm`.

Could you share more details about the broken components?

**Pull request merged**
