### PR TITLE
MON-1208: Bump Prometheus to v2.24.1

### PR DESCRIPTION
**Pull request by dgrisonnet**
Bumping to v2.24.0 fixes the following unit test failure:
```
--- FAIL: TestHandleMultipleQuitRequests (5.00s)
    web_test.go:492: 
        	Error Trace:	web_test.go:492
        	            				asm_amd64.s:1374
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:9090/-/quit": EOF
        	Test:       	TestHandleMultipleQuitRequests
    web_test.go:492: 
        	Error Trace:	web_test.go:492
        	            				asm_amd64.s:1374
        	Error:      	Received unexpected error:
        	            	Post "http://localhost:9090/-/quit": EOF
        	Test:       	TestHandleMultipleQuitRequests
FAIL
FAIL	github.com/prometheus/prometheus/web	15.159s
```

### CODE REVIEW

**Comment by s-urbaniak** [comment]
while we are not bound to feature freeze i'd say we wait until master for 4.8 opens, wdyt @simonpasquier ?

**Comment by simonpasquier** [comment]
@s-urbaniak sgtm

**Comment by dgrisonnet** [comment]
:+1: holding until 4.8 opens

/hold

**Comment by dgrisonnet** [comment]
@s-urbaniak @simonpasquier, should we reconsider the hold on this bump since code-freeze was delayed?

**Comment by simonpasquier** [comment]
I think the hold is still valid.

**Comment by dgrisonnet** [comment]
Unholding since 4.8 is now open.

/unhold

**Pull request merged**
