### PR TITLE
Aos bump v2.14.0

### PR DESCRIPTION
**Pull request by simonpasquier**
Prometheus v2.14.0 introdues a new ReactJS UI (still experimental but accessible from the main UI). This complicates a bit the build process for 2 reasons:

* The Javascript code is generated at build time now but build systems don't have `yarn` installed and they can't download packages from the outside.
  * The static assets should be generated locally and committed to this repository. The container image build runs `make common-build` instead of `make build`.
  * :warning: The same should be done every time we update to a new Prometheus version :warning: 
* `.promu.yml` doesn't support space-separated build tags (see https://github.com/prometheus/promu/issues/172) and comma-separated build tags are only supported starting with Go 1.13
  * I've turned the `builtinassets` tag into `ondiskassets`. As soon as the OpenShift build pipeline supports Go 1.13, this can be reverted.

### CODE REVIEW

**Comment by simonpasquier** [comment]
Given the UI changes, I'll check the PR with cluster-bot.
/hold

**Comment by brancz** [comment]
Bug and performance improvements are generally desirable for us though so if you confirm via cluster bot, I’m happy with this.

/lgtm

**Comment by simonpasquier** [comment]
It's ok now:

image

ping @pgier @s-urbaniak for approval

**Pull request merged**
