### PR TITLE
Bump to v2.20.0

### PR DESCRIPTION
**Pull request by simonpasquier**

### CODE REVIEW

**Comment by lilic** [comment]
As part of this we need to change also in CMO the version we specify for Prometheus, but before that the Prometheus operator does not run tests against this version so might be good to add that as well.

**Comment by simonpasquier** [comment]
The PR against prometheus-operator is https://github.com/coreos/prometheus-operator/pull/3356

**Comment by simonpasquier** [comment]
PR against CMO: https://github.com/openshift/cluster-monitoring-operator/pull/881

**Comment by simonpasquier** [comment]
@lilic prometheus-operator has now executed tests against this version. Please review :)

**Pull request merged**
