### PR TITLE
Bug 1964332: Update Version to 2.26.1

### PR DESCRIPTION
**Pull request by raptorsun**
This pull request aligns openshift/prometheus master branch to prometheus/prometheus tag v2.26.1. 

This introduce a fix to [bug 1964332](https://bugzilla.redhat.com/show_bug.cgi?id=1964332).

Update reviewer list in the meanwhile.

### CODE REVIEW

**Comment by raptorsun** [comment]
need fix in CI configurations, [see this PR](https://github.com/openshift/release/pull/18994)

**Comment by juzhao** [comment]
tested with the PR, prometheus version is 2.26.1 now, but we also need to change label version for clusterrole/clusterrolebindings/deploy/service/ServiceAccount/prometheusrule and related resources, they are still 2.26.0
```
# token=`oc sa get-token prometheus-k8s -n openshift-monitoring`
# oc -n openshift-monitoring exec -c prometheus prometheus-k8s-0 -- curl -k -H "Authorization: Bearer $token" 'https://prometheus-k8s.openshift-monitoring.svc:9091/api/v1/query?query=prometheus_build_info' | jq '.data.result[].metric | {pod,version}'
{
  "pod": "prometheus-k8s-1",
  "version": "2.26.1"
}
{
  "pod": "prometheus-k8s-0",
  "version": "2.26.1"
}

# oc -n openshift-monitoring get po --show-labels | grep prometheus-k8s
prometheus-k8s-0                               7/7     Running   1          26m   app.kubernetes.io/component=prometheus,app.kubernetes.io/instance=k8s,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,app.kubernetes.io/part-of=openshift-monitoring,app.kubernetes.io/version=2.26.0,app=prometheus,controller-revision-hash=prometheus-k8s-57db455f99,operator.prometheus.io/name=k8s,operator.prometheus.io/shard=0,prometheus=k8s,statefulset.kubernetes.io/pod-name=prometheus-k8s-0
prometheus-k8s-1                               7/7     Running   1          26m   app.kubernetes.io/component=prometheus,app.kubernetes.io/instance=k8s,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,app.kubernetes.io/part-of=openshift-monitoring,app.kubernetes.io/version=2.26.0,app=prometheus,controller-revision-hash=prometheus-k8s-57db455f99,operator.prometheus.io/name=k8s,operator.prometheus.io/shard=0,prometheus=k8s,statefulset.kubernetes.io/pod-name=prometheus-k8s-1

# oc -n openshift-monitoring get svc prometheus-k8s -oyaml | grep labels -A4
  labels:
    app.kubernetes.io/component: prometheus
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 2.26.0
```

**Comment by raptorsun** [comment]
> tested with the PR, prometheus version is 2.26.1 now, but we also need to change label version for clusterrole/clusterrolebindings/deploy/service/ServiceAccount/prometheusrule and related resources, they are still 2.26.0
> 
> ```
> # token=`oc sa get-token prometheus-k8s -n openshift-monitoring`
> # oc -n openshift-monitoring exec -c prometheus prometheus-k8s-0 -- curl -k -H "Authorization: Bearer $token" 'https://prometheus-k8s.openshift-monitoring.svc:9091/api/v1/query?query=prometheus_build_info' | jq '.data.result[].metric | {pod,version}'
> {
>   "pod": "prometheus-k8s-1",
>   "version": "2.26.1"
> }
> {
>   "pod": "prometheus-k8s-0",
>   "version": "2.26.1"
> }
> 
> # oc -n openshift-monitoring get po --show-labels | grep prometheus-k8s
> prometheus-k8s-0                               7/7     Running   1          26m   app.kubernetes.io/component=prometheus,app.kubernetes.io/instance=k8s,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,app.kubernetes.io/part-of=openshift-monitoring,app.kubernetes.io/version=2.26.0,app=prometheus,controller-revision-hash=prometheus-k8s-57db455f99,operator.prometheus.io/name=k8s,operator.prometheus.io/shard=0,prometheus=k8s,statefulset.kubernetes.io/pod-name=prometheus-k8s-0
> prometheus-k8s-1                               7/7     Running   1          26m   app.kubernetes.io/component=prometheus,app.kubernetes.io/instance=k8s,app.kubernetes.io/managed-by=prometheus-operator,app.kubernetes.io/name=prometheus,app.kubernetes.io/part-of=openshift-monitoring,app.kubernetes.io/version=2.26.0,app=prometheus,controller-revision-hash=prometheus-k8s-57db455f99,operator.prometheus.io/name=k8s,operator.prometheus.io/shard=0,prometheus=k8s,statefulset.kubernetes.io/pod-name=prometheus-k8s-1
> 
> # oc -n openshift-monitoring get svc prometheus-k8s -oyaml | grep labels -A4
>   labels:
>     app.kubernetes.io/component: prometheus
>     app.kubernetes.io/name: prometheus
>     app.kubernetes.io/part-of: openshift-monitoring
>     app.kubernetes.io/version: 2.26.0
> ```

these labels will be updated in CMO repository. Thank you !

**Comment by raptorsun** [comment]
PR updating prometheus version in CMO has been created. please refer to [this link.](https://github.com/openshift/cluster-monitoring-operator/pull/1208)

**Pull request merged**
